In [4]:
import requests
import pandas as pd
import time

# 1. 헤더 설정 (개발자 도구에서 확인한 최신 인증 정보)
headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'origin': 'https://www.yogiyo.co.kr',
    'referer': 'https://www.yogiyo.co.kr/',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
    'x-api-key': 'qua9EeW1ohth4ain', # 만약 401 에러가 나면 이 값을 새로 복사하세요
    'x-ygy-app-version': '9.0.0',
    'x-ygy-os-type': 'IOS',
    'x-ygy-route': 'v2',
}

# 2. 기본 파라미터 설정
params = {
    'adm_code': '1162069500',
    'customer_id': '923892007',
    'lat': '37.4869016',
    'lng': '126.92737994',
    'length': '60',
    'sort': 'RANK_DESC',
    'vertical_types': 'FOOD',
    'membership_code': 'NONE',
    'serving_types': 'VD',
    'use_bargainyo': 'false'
}

url = 'https://api.yogiyo.co.kr/shopyo/v1/shops'
all_shops = []

# 3. 무한 스크롤 수집 루프 (예: start 0부터 300까지 테스트)
# 900대에서 에러가 났다면 데이터가 없는 구간일 수 있으니 0부터 확인해보세요.
for start_val in range(0, 600, 60):
    params['start'] = str(start_val)
    print(f"현재 {start_val}번째 데이터 요청 중...")
    
    try:
        response = requests.get(url, params=params, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            shops_list = data.get('shops', [])
            
            if not shops_list:
                print("더 이상 가져올 데이터가 없습니다. 수집을 종료합니다.")
                break
                
            all_shops.extend(shops_list)
            print(f"성공: {len(shops_list)}개 추가됨 (누적: {len(all_shops)}개)")
            
        else:
            print(f"응답 실패: {response.status_code}, 메시지: {response.text}")
            break
            
    except Exception as e:
        print(f"에러 발생: {e}")
        break
        
    # 서버 차단 방지를 위한 휴식 시간 (통계 분석을 위한 대량 수집 시 필수)
    time.sleep(1.5)

# 4. 결과 통합 및 분석 준비
if all_shops:
    df = pd.DataFrame(all_shops)
    
    # KeyError 방지: 컬럼 존재 여부 확인 후 출력
    target_cols = ['name', 'review_avg', 'delivery_fee', 'min_order_amount']
    available_cols = [col for col in target_cols if col in df.columns]
    
    print("\n" + "="*30)
    print("최종 수집 완료")
    print(df[available_cols].head())
    
    # 엑셀 파일로 저장하여 블로그 포스팅이나 분석에 활용
    # df.to_excel("yogiyo_data_신림.xlsx", index=False)
else:
    print("수집된 데이터가 없습니다.")

현재 0번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 60개)
현재 60번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 120개)
현재 120번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 180개)
현재 180번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 240개)
현재 240번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 300개)
현재 300번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 360개)
현재 360번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 420개)
현재 420번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 480개)
현재 480번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 540개)
현재 540번째 데이터 요청 중...
성공: 60개 추가됨 (누적: 600개)

==============================
최종 수집 완료
               name
0       대치동엄마도시락-본점
1  앵그리포테이토치킨&버거-신림점
2          호호솥밥-관악점
3          육회한날연어어때
4           괴짜반점-본점

In [5]:
df

,id,name,location,vertical_type,vertical_sub_type,vendor_categories,tags,bpr_ranking,image,review,open_status,franchise,serving_type,distance,catalog_vendor_id,exposure_type,ad_id,point,representative_menus
0,1502665,대치동엄마도시락-본점,"{'lat': '37.4839342', 'lng': '126.93936786'}",FOOD,None,"[찜/탕, 한식, 도시락/죽, 포장]",[RELAYO],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 4.9, 'count': 195, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1108.02,None,CONTRACT,None,{'total': 0},"[{'id': 2038071069, 'name': '[BEST] 연탄 벌집(삼겹) ..."
1,1505082,앵그리포테이토치킨&버거-신림점,"{'lat': '37.4837321', 'lng': '126.92774951'}",FOOD,None,"[피자/양식, 버거, 분식, 포장, 1인분주문]",[],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 5.0, 'count': 203, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",353.94,None,CONTRACT,None,{'total': 0},"[{'id': 2098832456, 'name': '나홀로 1인 세트(시그니처)',..."
2,1517961,호호솥밥-관악점,"{'lat': '37.4854819', 'lng': '126.93790844'}",FOOD,None,"[한식, 고기/구이, 일식/돈까스, 포장, 프랜차이즈, 신규맛집]",[NEW],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 5.0, 'count': 20, 'image_co...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",942.28,None,CONTRACT,None,{'total': 0},"[{'id': 2152991873, 'name': '[시그니처] 스테이크 솥밥', ..."
3,568358,육회한날연어어때,"{'lat': '37.48203242479008', 'lng': '126.92966...",FOOD,None,"[포장, 일식/돈까스, 야식, 회/초밥]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 5.0, 'count': 15593, 'image...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",581.24,None,CONTRACT,None,{'total': 0},"[{'id': 930778160, 'name': '스테이크육회초밥', 'image_..."
4,1214991,괴짜반점-본점,"{'lat': '37.4839734', 'lng': '126.93930939'}",FOOD,None,"[한식, 중국집, 야식, 찜/탕, 포장]",[RELAYO],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.8, 'count': 3847, 'image_...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1101.79,None,CONTRACT,None,{'total': 0},"[{'id': 935692199, 'name': '[라드로 볶은] 찐한 풍미 짜장면..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,1188893,도미노피자-보라매점,"{'lat': '37.4875791', 'lng': '126.93274977'}",FOOD,None,"[피자/양식, 프랜차이즈]","[RELAYO, CESCO, HYGIENE]",None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.8, 'count': 278, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...","{'id': 972, 'ygy_franchise_id': 652, 'name': '...","{'vd': {'ypx_minimum_order_amount': 0, 'estima...",479.74,None,CONTRACT,None,{'total': 0},"[{'id': 840964031, 'name': '리얼불고기 L', 'image_p..."
596,517823,감자탕골목뼈찜대장,"{'lat': '37.4867575', 'lng': '126.94058449'}",FOOD,None,"[족발/보쌈, 한식, 찜/탕, 포장, 야식, 1인분주문]",[RELAYO],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.9, 'count': 547, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1165.18,None,CONTRACT,None,{'total': 0},"[{'id': 930215723, 'name': '[관악구 유일] 골목대장 뼈구이'..."
597,1325510,BHC-상도점,"{'lat': '37.4989724', 'lng': '126.93958825'}",FOOD,None,"[프랜차이즈, 치킨, 포장]","[RELAYO, CESCO]",None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.9, 'count': 1433, 'image_...","{'current_open_status': 'OPENING_TIME', 'next_...","{'id': 610, 'ygy_franchise_id': 37, 'name': '[...","{'vd': {'ypx_minimum_order_amount': None, 'est...",1720.94,None,CONTRACT,None,{'total': 0},"[{'id': 939316566, 'name': '뿌링클', 'image_path'..."
598,1240137,마라촌마라탕-신대방역점,"{'lat': '37.48633674334252', 'lng': '126.91346...",FOOD,None,"[중국집, 아시안, 포장]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 4.9, 'count': 794, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1229.54,None,CONTRACT,None,{'total': 0},"[{'id': 939141119, 'name': '남다른 궈보러우', 'image_..."
599,1417574,도래곱창-신림점,"{'lat': '37.4693353', 'lng': '126.93633444'}",FOOD,None,"[한식, 고기/구이, 야식, 포장, 프랜차이즈, 1인분주문]",[RELAYO],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.9, 'count': 42, 'image_co...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",2107.06,None,CONTRACT,None,{'total': 0},"[{'id': 1424472947, 'name': '[2인 안주추천] 야채곱창+알곱..."

In [6]:
import requests
import pandas as pd
import time

# 1. 인증 및 헤더 설정
headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'origin': 'https://www.yogiyo.co.kr',
    'referer': 'https://www.yogiyo.co.kr/',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
    'x-api-key': 'qua9EeW1ohth4ain',
    'x-ygy-app-version': '9.0.0',
    'x-ygy-os-type': 'IOS',
    'x-ygy-route': 'v2',
}

# 2. 파라미터 초기 설정
params = {
    'adm_code': '1162069500',
    'customer_id': '923892007',
    'lat': '37.4869016',
    'lng': '126.92737994',
    'length': '60',
    'sort': 'RANK_DESC',
    'vertical_types': 'FOOD',
    'membership_code': 'NONE',
    'serving_types': 'VD',
    'use_bargainyo': 'false'
}

url = 'https://api.yogiyo.co.kr/shopyo/v1/shops'

all_shops = []
start_val = 0
is_end = False

print("데이터 수집 시작")

# 3. 데이터가 없을 때까지 반복 수행
while not is_end:
    params['start'] = str(start_val)
    
    try:
        response = requests.get(url, params=params, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            shops_list = data.get('shops', [])
            
            # 더 이상 가져올 데이터가 없는 경우 루프 종료
            if not shops_list:
                print(f"\n수집 완료: {start_val} 지점에서 데이터가 더 이상 없습니다.")
                is_end = True
                break
                
            all_shops.extend(shops_list)
            print(f"현재 위치: {start_val} / 누적 상점 수: {len(all_shops)}", end='\r')
            
            # 다음 페이지를 위해 인덱스 증가
            start_val += 60
            
        elif response.status_code in [401, 403]:
            print("\n인증 키 만료 혹은 접근 차단이 발생했습니다.")
            break
        else:
            print(f"\n오류 발생 (상태 코드: {response.status_code})")
            break
            
    except Exception as e:
        print(f"\n네트워크 예외 발생: {e}")
        break
        
    # 서버 부하 방지를 위한 대기 시간
    time.sleep(1.5)

# 4. 결과 저장
if all_shops:
    df = pd.DataFrame(all_shops)
    print("\n수집 결과 요약")
    print(f"총 상점 수: {len(df)}")
    
    # 분석용 주요 컬럼 존재 확인 및 출력
    cols = ['name', 'review_avg', 'delivery_fee', 'min_order_amount']
    available = [c for c in cols if c in df.columns]
    print(df[available].head())
    
    # 파일 저장
    df.to_csv("yogiyo_full_data.csv", index=False, encoding='utf-8-sig')
    print("파일 저장 완료: yogiyo_full_data.csv")
else:
    print("\n수집된 데이터가 없습니다.")

데이터 수집 시작
현재 위치: 1860 / 누적 상점 수: 1895
수집 완료: 1920 지점에서 데이터가 더 이상 없습니다.

수집 결과 요약
총 상점 수: 1895
               name
0       대치동엄마도시락-본점
1  앵그리포테이토치킨&버거-신림점
2          호호솥밥-관악점
3          육회한날연어어때
4           괴짜반점-본점
파일 저장 완료: yogiyo_full_data.csv

,id,name,location,vertical_type,vertical_sub_type,vendor_categories,tags,bpr_ranking,image,review,open_status,franchise,serving_type,distance,catalog_vendor_id,exposure_type,ad_id,point,representative_menus
0,1502665,대치동엄마도시락-본점,"{'lat': '37.4839342', 'lng': '126.93936786'}",FOOD,None,"[찜/탕, 한식, 도시락/죽, 포장]",[RELAYO],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 4.9, 'count': 195, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1108.02,None,CONTRACT,None,{'total': 0},"[{'id': 2038071069, 'name': '[BEST] 연탄 벌집(삼겹) ..."
1,1505082,앵그리포테이토치킨&버거-신림점,"{'lat': '37.4837321', 'lng': '126.92774951'}",FOOD,None,"[피자/양식, 버거, 분식, 포장, 1인분주문]",[],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 5.0, 'count': 203, 'image_c...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",353.94,None,CONTRACT,None,{'total': 0},"[{'id': 2098832456, 'name': '나홀로 1인 세트(시그니처)',..."
2,1517961,호호솥밥-관악점,"{'lat': '37.4854819', 'lng': '126.93790844'}",FOOD,None,"[한식, 고기/구이, 일식/돈까스, 포장, 프랜차이즈, 신규맛집]",[NEW],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 5.0, 'count': 20, 'image_co...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",942.28,None,CONTRACT,None,{'total': 0},"[{'id': 2152991873, 'name': '[시그니처] 스테이크 솥밥', ..."
3,568358,육회한날연어어때,"{'lat': '37.48203242479008', 'lng': '126.92966...",FOOD,None,"[포장, 일식/돈까스, 야식, 회/초밥]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 5.0, 'count': 15593, 'image...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",581.24,None,CONTRACT,None,{'total': 0},"[{'id': 930778160, 'name': '스테이크육회초밥', 'image_..."
4,1214991,괴짜반점-본점,"{'lat': '37.4839734', 'lng': '126.93930939'}",FOOD,None,"[한식, 중국집, 야식, 찜/탕, 포장]",[RELAYO],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 4.8, 'count': 3847, 'image_...","{'current_open_status': 'OPENING_TIME', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",1101.79,None,CONTRACT,None,{'total': 0},"[{'id': 935692199, 'name': '[라드로 볶은] 찐한 풍미 짜장면..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,1335521,헬로크랩-개봉역점,"{'lat': '37.4929162', 'lng': '126.85993106'}",FOOD,None,"[찜/탕, 한식, 회/초밥, 포장, 프랜차이즈]",[CESCO],None,{'logo_url': 'https://rev-static.yogiyo.co.kr/...,"{'average_rating': 5.0, 'count': 8, 'image_cou...","{'current_open_status': 'TEMP_HOLIDAY', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': 0, 'estima...",5988.40,None,CONTRACT,None,{'total': 0},"[{'id': 991304079, 'name': '[서울, 경기최저가]A급 활 대게..."
1891,1287151,니드쿠키(kneadcookie),"{'lat': '37.5028137', 'lng': '126.89775928'}",FOOD,None,"[분식, 카페/디저트]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 5.0, 'count': 3, 'image_cou...","{'current_open_status': 'CLOSED', 'next_open_s...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",3155.87,None,CONTRACT,None,{'total': 0},"[{'id': 937760707, 'name': '아메리카노', 'image_pat..."
1892,1086464,초장집-영등포점,"{'lat': '37.517175509084986', 'lng': '126.9075...",FOOD,None,"[찜/탕, 한식, 회/초밥, 야식, 포장, 프랜차이즈]",[CESCO],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 4.9, 'count': 57, 'image_co...","{'current_open_status': 'TEMP_HOLIDAY', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",3792.88,None,CONTRACT,None,{'total': 0},"[{'id': 933603786, 'name': '연포탕', 'image_path'..."
1893,1227416,깡우동-시흥사거리점,"{'lat': '37.4520775', 'lng': '126.90266415'}",FOOD,None,"[찜/탕, 한식, 분식, 야식, 포장, 프랜차이즈]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 4.5, 'count': 2, 'image_cou...","{'current_open_status': 'TEMP_HOLIDAY', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",4444.65,None,CONTRACT,None,{'total': 0},"[{'id': 936240329, 'name': '우동', 'image_path':..."
1894,1470450,요아빙수-사랑점,"{'lat': '37.5206363', 'lng': '126.8607197'}",FOOD,None,"[카페/디저트, 포장, 야식]",[],None,"{'logo_url': None, 'thumbnail_url': 'https://r...","{'average_rating': 0.0, 'count': 0, 'image_cou...","{'current_open_status': 'TEMP_HOLIDAY', 'next_...",None,"{'vd': {'ypx_minimum_order_amount': None, 'est...",6974.85,None,CONTRACT,None,{'total': 0},"[{'id': 1751071386, 'name': '벌집꿀+그래놀라+요거트아이스크림..."